### ISSUE TITLE
Add UKWA Logo and Color Scheme

### ISSUE THREAD

**Issue by ikreymer** [ukwa/ukwa-pywb#10]
Add themed UI for all templates, banner for replay

**Comment by ikreymer** [comment]
Is there a newer version of logo that should be used, or should use the banner and logo from OpenWayback deployment?

**Comment by anjackson** [comment]
Could you use the colouring and logo from our Beta? See: https://beta.webarchive.org.uk/wayback/archive/*/http://www.bl.uk/ or https://beta.webarchive.org.uk/ for the general idea.

**Comment by ikreymer** [comment]
UKWA header banner added to all pages, and new banner with UKWA logo for replay and calendar link.
The replay banner and header also contain links to switch locales, and some sample translations for CY have been added also.
