### ISSUE TITLE
Additional MVP document reader functionality 

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#100]
Following initial evaluate, we need to build on the original PDF/ePub implementation #68 and add the following features:

- Citation:
    - [x] Chapter and paragraph citation #98
    - [x] Ability to enter chapter and paragraph numbers to resolve a citation.
- Search:
    - [x] Searching for a keyword through an entire ebook and being able to view all of the results (it’s possible to do some limited search using ctrl+f) (seems possible, see https://github.com/futurepress/epub.js/wiki/Tips-and-Tricks-(v0.3)#searching-the-entire-book)
- Print:
    - [x] Being able to preview all pages in print preview (might have to be per-chapter, using whole-chapter view, see https://github.com/ukwa/ukwa-pywb/issues/68#issuecomment-1186868283)
    - [x] Being able to print a range of pages (might have to be per-chapter , using whole chapter view, as above).

The PDF, viewer does meet this requirements already, although printing can be slow because it currently renders all pages first. 

The ePub viewer generally works well but is somewhat confusing because it is so different from the PDF viewer UI. e.g. both can zoom, but the PDF viewer has dedicated buttons whereas the ePub viewer relies on the browser zoom. Ideally, both interfaces would be consistent.

One option is to switch to a UV implementation that supports both formats in a consistent manner. This should be evaluated, with the above requirements (and the core requirements the existing system already meets) kept in mind. I think those core requirements are:

- Outline (if available)
- Thumbnails (if available) with position/page number shown  on hover
- Zoom
- Current position/page indicator

**Comment by anjackson** [comment]
Note that in #99 I experimented with a different ePub reader library called Vivliostyle. This could be considered if adding the above functionality to the existing reader is problematic.

**Comment by anjackson** [comment]
@tw4l On the _Search_ feature, it is possible to bind it to `CTRL-F` to use your search rather than the browser page search?

**Comment by tw4l** [comment]
@anjackson Merged as part of https://github.com/ukwa/ukwa-pywb/pull/108 along with a fix for the Reference bug we had before that required viewing a chapter before "Jump to citation" would work.

Only thing to note is that for now jumping to a citation will only highlight the first character of the paragraph - we can discuss coming back to highlighting the whole paragraph if need be after printing but it was proving to be difficult and I wanted to move on to make sure we hit the next milestone.
