### ISSUE TITLE
Allow alternative paths/prefixes for WebHDFS stores

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#102]
The [current PywB loader for WebHDFS hard-codes the `webhdfs` path](https://github.com/webrecorder/pywb/blob/510c9dc9f11b38c9135eae88debd30f6a7ed54ea/pywb/utils/loaders.py#L434). It would be neater if we could set it from the configuration rather than append it. i.e. config of `webhdfs://server/wa/webhdfs/v1` would be used as-is (`http://server/wa/webhdfs/v1`) rather than becoming `http://server/webhdfs/v1/wa/webhdfs/v1`.

n.b. this is fairly easy to work around so it not urgent.

**Comment by ldbiz** [comment]
@anjackson would you provide an example of how this would be seen in action to reproduce and test?

**Comment by anjackson** [comment]
Thanks for checking, but at thing point I think it's not worth pursuing this any further. Any configuration we need can be handled in the https://github.com/ukwa/ukwa-warc-server that locates the WARCs.
