### ISSUE TITLE
LDVB_12: Override browser ctrl+f in epub viewer to use viewer's search function

### ISSUE THREAD

**Issue by tw4l** [ukwa/ukwa-pywb#116]
Overriding browser keyboard shortcuts is notoriously difficult, but we should try to make this as consistent across browsers as possible.

**Comment by tw4l** [comment]
This seems to already be working in Chromium, Chrome, and Firefox for me on macOS after clearing the browser cache. Should verify if this is a Windows issue or cache related.

@anjackson would it be possible to clear the cache on the browsers used for testing?

**Comment by anjackson** [comment]
Again, it looks like the PWB kiosk browser using the BL reading rooms is preventing this from working.

**Comment by tw4l** [comment]
Is the ctrl-p override working to go to print view, or is it just ctrl-f?

**Comment by anjackson** [comment]
That seems to work okay. I press Ctrl-P and it brings the print dialogue up while at the same time the print view appears. That seems to be the same as in Chrome.

However, if you press Ctrl-P you seem to get the framed layout? Whereas if you press the print button you get a multi-page document.
