### ISSUE TITLE
Support injection of custom, per-site JS

### ISSUE THREAD

**Issue by ikreymer** [ukwa/ukwa-pywb#13]
Add support for per-site JS injection, probably by SURT prefix.

Can be specified in a format similar to the access system:
`com,example)/ - {"insert": "custom_file.js"}`

There are already extensive server-side rewriting options in `rules.yaml`, perhaps combine with those in some way?

**Comment by ikreymer** [comment]
I should note while this is technically possible, the approach in pywb has been to avoid this sort of thing as much as possible and to add non-domain specific solutions wherever possible.

That being said, there are a few cases where custom server-side rewriting has been necessary, and those are configured in the rules.yaml file (which needs more documentation).

A more flexible approach would be to configure a custom script at the collection level, say `fixup.js` and within that script perform any custom actions. Since the same script would be inserted in every HTML file (much like a banner) and can run first, it will allow for more flexible server-side.

For example, a single script `fixup.js` could be configured to also check browser and have a set of states based on url and browser combinations, using the injected capture info `wbinfo` object and `navigator.userAgent`

```
if (wbinfo.url.indexOf("http://example.com/") == 0 && wbinfo.timestamp >= "2012" && navigator.userAgent.indexOf("Firefox") >= 0) {
//do something custom
}
```
The custom rules can then be set up entirely within this script. Based on this flexibility, I would recommend this approach.

**Comment by anjackson** [comment]
Happy to just have the capability if needed, and this approach sounds fine.

I agree that site-specific rules should be avoided if possible. FWIW, our main use case is streaming-backed Flash video, e.g. https://www.webarchive.org.uk/wayback/archive/20100219182652/http://www.oneandother.co.uk/participants/Blossom

Our current system uses a fix-up script to change the HTML and relies on our own back-end streaming server. Clearly, we should move this to a pure HTML solution. It may be worth considering a piece of follow-on work to WARC up our video streams (which were downloaded manually) and make it work in pywb.

**Comment by ikreymer** [comment]
Ah yes, that makes sense. pywb actually has a similar, experimental script for a similar purpose, [vidrw.js](https://github.com/webrecorder/pywb/blob/master/pywb/static/vidrw.js).

It was designed to use youtube-dl metadata info to replace Flash video players with a custom player, however, requires that the video streams be first captured with youtube-dl. (It's now disabled by default in pywb and Webrecorder as its use is limited as most video is now HTML5).

It'd be possible to adapt this solution for a different streaming source, where certain flash embeds are replaced with an HTML5 video streaming from a different source.

For now, added this placeholder: [fixup.js](https://github.com/ukwa/ukwa-pywb/blob/master/static/fixup.js), which can be used to do custom per-domain handling client-side.

**Comment by ikreymer** [comment]
Fixup script now also injected in proxy mode, and has a comment for how to check if in proxy mode.

Added tests to ensure it is injected in replay, proxy replay, but not top frame:
https://github.com/ukwa/ukwa-pywb/blob/master/integration-test/robot/tests/fixup_inject.robot
