### ISSUE TITLE
Problem viewing calendar pages

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#19]
As of right now, running the Docker ukwa/ukwa-pywb image against our production APIs, the calendar doesn't work. It partially loads and there's this in the console:

    Syntax error, unrecognized expression: #month_2010_December }}

Arising at line 111 of query.js:

    if (! $('#month_' + currentYear + '_' + currentMonth).length){

Which looks like a missed `)`.

Looks good otherwise tho!

**Comment by ikreymer** [comment]
The actual typo was in a template: `'12': "{{ _('December') }} }}"`, now fixed.
