### ISSUE TITLE
Prefix search possible?

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#32]
OpenWayback permits a prefix search mode, where it lists the URLs under a given prefix. Can pywb do the same?

**Comment by ikreymer** [comment]
Yes, this is supported via the cdx query, eg.
http://localhost:8080/example/cdx?url=http://iana.org/&matchType=prefix

Unfortunately, it looks like the UI rendering of it got broken with a switch to the newer UI and needs to be updated. It should show up under: `http://localhost:8080/example/*/http://iana.org/*` but currently does not. (webrecorder/pywb#296)

Is this something you'd need pretty soon?

**Comment by ikreymer** [comment]
This has been released in mainline pywb 2.2.x, will be available once the ukwa/pywb changes are merged in for, pywb 2.3.x

**Comment by anjackson** [comment]
Note that this is now live on BETA.

**Comment by anjackson** [comment]
Looks good. Collapsing by URL would be more elegant, but it's essentially working.
