### ISSUE TITLE
Page still titled ‘Loading...’ when load is finished 

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#33]
On a few pages the page title/frame still says ‘Loading...’ even though it’s stopped. 

One example is a PDF https://www.webarchive.org.uk/wayback/archive/20180523082513/https:/assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/705269/Post_16_education_highest_level_of_achievement_by_age_25.pdf

**Comment by ikreymer** [comment]
Ah yes, this will happen with any non-HTML that is loaded currently. The top frame expects a postMessage() from the inner frame when the page is loaded, but that will not happen for any non-html content. There's a few options, eg. timeout, peeking into iframe, to do this.

**Comment by anjackson** [comment]
As pointed out in https://twitter.com/ibnesayeed/status/1082767395603795968 this appears to happen for error pages too.

**Comment by ikreymer** [comment]
This has been released in mainline pywb 2.2.x, will be available once the ukwa/pywb changes are merged in for, pywb 2.3.x

**Comment by anjackson** [comment]
Hm, still happening under 2.4.0-BETA? https://beta.webarchive.org.uk/wayback/archive/20180523082513/https:/assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/705269/Post_16_education_highest_level_of_achievement_by_age_25.pdf

**Comment by ikreymer** [comment]
Appears that the banner needs to be updated to include this functionality, looking at this.

**Comment by ikreymer** [comment]
Should be fixed with latest docker image and `2.4.0-beta` branch.

**Comment by anjackson** [comment]
Verified, as of `2.4.0-beta-5` it falls back on the URL for https://beta.webarchive.org.uk/wayback/archive/20180523082513/https:/assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/705269/Post_16_education_highest_level_of_achievement_by_age_25.pdf
