### ISSUE TITLE
Graceful reload of configuration

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#36]
Can we gracefully reload the whitelists/blacklists?

**Comment by ikreymer** [comment]
Do you mean for the .aclj files?
If so, then yes, I believe the files should actually be automatically reloaded from disk.
The entire config.yaml currently is not auto-reloadable.

**Comment by anjackson** [comment]
Oh, hm. That didn't appear to be working. But maybe I missed something. I'll check after Christmas.

**Comment by anjackson** [comment]
Scratch that - the file wasn't getting updated properly. Sorry!

**Comment by ikreymer** [comment]
Hm, I've tested it now with both editing an existing file and replacing with new file, and seems to be working as expected (locally). Are the data files being placed in a Docker volume?

**Comment by anjackson** [comment]
Yes, like this:

```
volumes:
     - ./pywb/config.yaml:/webarchive/config.yaml
     - /root/wayback-config/allows.aclj:/ukwa_pywb/acl/allows.aclj
     - /root/wayback-config/exclude-blacklist.aclj:/ukwa_pywb/acl/blocks.aclj
```

**Comment by ikreymer** [comment]
Yep, I was just about to suggest that, I think if you map an individual file, Docker won't be able to remount it without restarting the container. But `/root/wayback-config/acl/:/ukwa_pywb/acl/` should work for dropping in a new file.

**Comment by anjackson** [comment]
Thanks @ikreymer that should work I think. Either way, clearly not a ukwa-pywb bug so I'll close this.
