### ISSUE TITLE
Should / and /index.html etc. get normalised down to the same SURT?

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#43]
As per https://github.com/ukwa/w3act/issues/614

Things like `/index.html` should really get flattened down to `/` I think?

Maybe not. Looking at the OpenWayback documentation, I don't think it's usual to canonicalise the `/index.html` in this way https://github.com/iipc/openwayback/wiki/Technical-overview#canonicalization-scheme

**Comment by anjackson** [comment]
No. Likely a terrible idea. Search/catalogue can manage this stuff if needed.

**Comment by ato** [comment]
We do but specifically only for httrack content.
