### ISSUE TITLE
Make calendar layout responsive

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#46]
The calendar layout would look better if it switched to a long layout for small screens.

![0092E421-143B-4249-823A-709CCE9900E9](https://user-images.githubusercontent.com/87843/66307732-1a78b900-e8fd-11e9-8df4-ea6e2be104af.png)

**Comment by ikreymer** [comment]
Fixed by webrecorder/pywb#515

**Comment by anjackson** [comment]
Looks good! Fixed in 2.4.0-beta-2.
