### ISSUE TITLE
Avoid ‘leaking’ internal details in production 

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#47]
It would be preferable if the internal configuration details were not accessible in this way.

![IMG_2854](https://user-images.githubusercontent.com/87843/66307944-b4406600-e8fd-11e9-9770-2117ac5fd43d.jpg)

**Comment by ikreymer** [comment]
Should now be fixed, please try latest 2.4.0-beta (updated Docker image to `webrecorder/pywb:2.4.0-rc0`)

**Comment by anjackson** [comment]
Looks good!.
