### ISSUE TITLE
Query string truncation in calendar view

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#48]
If we go to: 

https://beta.webarchive.org.uk/wayback/archive/*/https://www.gov.uk/search/all?organisations[]=foreign-commonwealth-office&order=updated-newest

We get 

> 80 captures of https://www.gov.uk/search/all?organisations[]=foreign-commonwealth-office&order=updated-newest

but the results point to: https://www.gov.uk/search/all?organisations[]=foreign-commonwealth-office

i.e. the additional parameter has been dropped somewhere. Doesn't seem to happen on older pywb

https://www.webarchive.org.uk/wayback/archive/*/https://www.gov.uk/search/all?organisations[]=foreign-commonwealth-office&order=updated-newest

If I go direct to the container, it also loses the second query parameter.

Playback URLs seem to work,

https://beta.webarchive.org.uk/wayback/archive/20191018085010/https://www.gov.uk/search/all?organisations[]=foreign-commonwealth-office&order=updated-newest

... so I think this is a problem with the new calendar page:

**Comment by ikreymer** [comment]
Should now be fixed, please try latest 2.4.0-beta (updated Docker image to `webrecorder/pywb:2.4.0-rc0`)

**Comment by anjackson** [comment]
Verified as fixed! Thanks!
