### ISSUE TITLE
Avoid 10K cap on numbers of results

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#49]
For some pages, we hit OutbackCDX's default `limit=10000` for numbers of results, e.g. https://beta.webarchive.org.uk/wayback/archive/*/https://www.theguardian.com/uk which stops in 2018.

How can we change pywb to use a larger limit?

**Comment by anjackson** [comment]
Similarly, prefix searches seem to top-out at 100,000? https://beta.webarchive.org.uk/wayback/archive/*?url=http://www.bl.uk/&matchType=prefix

But if I query the https://beta.webarchive.org.uk/wayback/archive/cdx?url=http://www.bl.uk/&matchType=prefix&limit=1000000 I get 145,793?!

**Comment by anjackson** [comment]
Also, this may be a separate thing, but I notice there's no 'collapsing' happening even when instances are pretty close together (i.e. every snapshot has it's own line with a (1) at the end).  Not sure this is set up right?

**Comment by ikreymer** [comment]
Looks like the limit is 100,000 if no other limit is specified, for both prefix and exact.
Can add a config.yaml setting:
`query_limit: 50000` to override. Or support different limits for exact and prefix?

Will look at collapsing, think that's a separate issue.

**Comment by anjackson** [comment]
That configuration setting would be fine.

**Comment by ikreymer** [comment]
Configuration setting added! Included in `webrecorder/pywb:2.4.0-rc1` Docker image.

**Comment by anjackson** [comment]
Tried this and it didn't appear to work. How should I configure it?

**Comment by ikreymer** [comment]
Yes, it should work for any backend. I've tested smaller limits, but not larger ones.. Just in case, does it work if you set it to be small, eg. 10?

**Comment by ikreymer** [comment]
Actually, looks like it does not currently work on the XmlQuery backend, as that requires slightly different semantics, not just adding `&limit=10000`.. will fix soon

**Comment by ikreymer** [comment]
Oops, didn't mean to close this yet. Re-opening so you can double-check that its working @anjackson

**Comment by anjackson** [comment]
Looks like it's fixed, based on https://beta.webarchive.org.uk/wayback/archive/*/https://www.theguardian.com/uk right now. Seems a bit slow but I think that might be something wholly separate.
