### ISSUE TITLE
Add support for user.name field in WebHDFS?

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#5]
After attempting to run the service directly against our APIs internally, I found a gap that #1 missed. Our production APIs require the user to add a `user.name=<USERNAME>` field as per [this documentation](https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#Authentication). Soon, our newer cluster may also require a `delegation=<TOKEN>` field. Would it be possible to add these to the configuration easily enough?

**Comment by ikreymer** [comment]
env vars `WEBHDFS_USER` and `WEBHDFS_TOKEN` can be used to specify the `user.name=` and/or the `delegation=` params.
