### ISSUE TITLE
Error when running recent 2.4.0 release

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#51]
Hm, playback not working at present, throwing `Internal Error: '_Q' is undefined`.

https://github.com/ukwa/ukwa-pywb/blob/80d566d103ed1818f3b8db4f20638faea519cc60/ukwa_pywb/ukwa_app.py#L162

Rolling back to 2.4.0-beta-2 resolves this.

 (thanks for noticing this promptly @GilHoggarth !)

**Comment by ikreymer** [comment]
Doh, my mistake, I thought I merged a PR (webrecorder/pywb#517) but didn't yet :(
Now merged, building a `webrecorder/pywb:2.4.0-rc2` image

**Comment by anjackson** [comment]
Yep, `2.4.0-beta-5` rolled out and looks good, thanks!
