### ISSUE TITLE
Problems playing back some Twitter records

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#61]
Having tested the site a bit, it seems this version of PyWB is having more problems with Twitter than before, getting Bad Gateway (e.g. https://dev.webarchive.org.uk/wayback/archive/20200516025247mp_/https://twitter.com/aberdyfisart/) and logging like:

```
access_website_pywb.1.v7h06fkj35kk@dev2    | 127.0.0.1 - - [2020-12-11 15:00:42] "POST /archive/resource/postreq?url=https%3A%2F%2Ftwitter.com%2Faberdyfisart%2F&closest=202
00516025247&matchType=exact HTTP/1.1" 200 17440 0.072072
access_website_pywb.1.v7h06fkj35kk@dev2    | Fri Dec 11 15:00:42 2020 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /wayback/archive/202
00516025247mp_/https://twitter.com/aberdyfisart/ (10.0.0.2)
access_website_pywb.1.v7h06fkj35kk@dev2    | OSError: write error
access_website_pywb.1.v7h06fkj35kk@dev2    | [pid: 16|app: 0|req: 822/2526] 10.0.0.2 () {66 vars in 1226 bytes} [Fri Dec 11 15:00:42 2020] GET /wayback/archive/202005160252
47mp_/https://twitter.com/aberdyfisart/ => generated 36506 bytes in 113 msecs (HTTP/1.0 200) 27 headers in 4083 bytes (4 switches on core 397)
```

This seems to be related to handling warcprox WARCs and https://github.com/netarchivesuite/solrwayback/issues/58 and is the inverse problem to https://github.com/webrecorder/pywb/issues/584 I think.

**Comment by anjackson** [comment]
The payload appears to be GZipped but not chunked, but is marked as GZipped and chunked (?). See attached.
[twitter-example-chunked-record.warc.gz](https://github.com/ukwa/ukwa-pywb/files/5681780/twitter-example-chunked-record.warc.gz)

**Comment by anjackson** [comment]
Hey @ikreymer - does this look like a PyWB bug?

**Comment by anjackson** [comment]
I've extracted the apparently problematic WARC and zipped it here: [twitter-error.zip](https://github.com/ukwa/ukwa-pywb/files/5897007/twitter-error.zip)

**Comment by ikreymer** [comment]
The decompressed, dechunked record does appear to be truncated, when loaded though pywb & replayweb.page and via warcio with: `warcio extract --payload witter-error.warc 0`
The response is missing a terminating </body></html>..
Haven't seen this before, will check if a chunk is not being decompressed, or if its just truncated in the record.

**Comment by anjackson** [comment]
Hm, seems like some problem with the various NGINXs.  I see

```
upstream sent too big header while reading response header from upstream
```

And adding some 

```
        # Up proxy buffering because we get ' upstream sent too big header while reading response header from upstream'
        proxy_buffer_size   128k;
        proxy_buffers   4 256k;
        proxy_busy_buffers_size   256k;
```

fixed it up.

Sorry for the confusion! Thanks.
