### ISSUE TITLE
Constant reloading

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-pywb#64]
This capture will constantly reload the same resources without rendering, which if left open in a tab, will continue to reload endlessly, putting strain on the service.
https://www.webarchive.org.uk/act/wayback/archive/20210407083152/https://yellowcard.mhra.gov.uk/

Previous captures going back to 2015 also suffer from the same issue

![image](https://user-images.githubusercontent.com/18530934/114011262-f208ac80-985c-11eb-83fb-7ccd9ddd018b.png)

**Comment by anjackson** [comment]
Again, this works fine on DEV https://dev.webarchive.org.uk/act/wayback/archive/20210407083152/https://yellowcard.mhra.gov.uk/  - so perhaps related to #63 ?

**Comment by ldbiz** [comment]
The other issue is closed, can this be or is it still a problem? @crarugal / @anjackson ?

**Comment by crarugal** [comment]
Thanks for flagging this Mindy, and thanks for fixing it, Andy. The page loads fine in production:
https://www.webarchive.org.uk/act/wayback/archive/20210407083152/https://yellowcard.mhra.gov.uk/
![image](https://github.com/ukwa/ukwa-pywb/assets/18530934/eaaa12dc-e851-48a4-a84f-16b779408c4c)
