### ISSUE TITLE
Always redirect to a fixed timestamp

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#66]
Each document will have a downstream 'live' URL of the form:

    http://document.server/ark://xxx.xxxx

We wish to ensure the single-concurrent-usage locks always apply to this URL, so the service must always use a fixed timestamp for items in the live collection that is being used to provide access

**Comment by ikreymer** [comment]
This would be handled by the NPLD player app as well, right, given, a link like `npld-viewer://live/<url>`, the NPLD viewer will know to connect to `https://<ukwa-pywb-server/live-ark/<todayts>/<url>` where `<todayts>` would be a 14-digit ts for the day, eg. `20220426000000` ? Or is there another way that a live ark: url would be obtained?

**Comment by anjackson** [comment]
As per [this overview[(https://github.com/ukwa/ukwa-services/tree/master/access/rrwb#overview), the ARK URLs are of the form: `https://PREFIX.ldls.org.uk/welcome.html?ark:/81055/vdc_100090432161.0x00000` or `https://PREFIX.ldls.org.uk/ark:/81055/vdc_100090432161.0x00000`. These should get redirected to `/doc/FIXED-TIMESTAMP/DLS_SERVICE_PREFIX/ark:/81055/vdc_100090432161.0x00000` where 'doc' is the live collection ([see current system config here](https://github.com/ukwa/ukwa-services/blob/master/access/rrwb/pywb/readingroom.yaml)).

The idea was that the FIXED-TIMESTAMP would always be forced to be the same, so the single-concurrent-use lock was always the same and could not be sidestepped by changing the timestamp.

All of this could probably be done in [the NGINX configuration](https://github.com/ukwa/ukwa-services/tree/master/access/rrwb/nginx).

**Comment by anjackson** [comment]
This was implemented.
