### ISSUE TITLE
Strange render

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-pywb#70]
Thought this is worth flagging, I was trying to render a QA PyWb  instance of https://www.webarchive.org.uk/act/wayback/archive/20211103115234/https://www.bcg.com/
- issue occurs in both Firefox and Chome (logged into ACT)

- I've not investigated this further, today is the first time I've come across this playback issue

https://www.webarchive.org.uk/act/targets/148097

Rendering has mashed the UKWA homepage with the archived content:
![image](https://user-images.githubusercontent.com/18530934/140734401-7036478a-3f3b-4b9b-a8ad-ebebfdaa8da8.png)

![image](https://user-images.githubusercontent.com/18530934/140734439-8d8e1b2b-a8fb-4a9b-bd1a-685d11d3a4da.png)
![image](https://user-images.githubusercontent.com/18530934/140734472-4cf7614e-2674-405e-b483-e6230bb4c420.png)

![image](https://user-images.githubusercontent.com/18530934/140735077-b8238637-cc8b-4801-b93f-08335abef68e.png)

**Comment by anjackson** [comment]
So weird. Looks like some calls are slipping past PyWB's rewriting, and calling URLs like:

https://www.webarchive.org.uk/en-gb/?_fragmentId=00000179-fc4b-dc82-a9ff-ffff65bc000d&_fragmentParent=00000179-fc4b-dc82-a9ff-ffff65770002&_fragmentSignature=d24b4d90df519b54644f6a9af689f3f69302db54&_fragmentContext=WyIvY29yZS9wYWdlL0hvbWVQYWdlLmhicyIsIm1haW4iLCJtYWluOjEiLCIvdGFyZ2V0ZWQvVGFyZ2V0ZWRNb2R1bGUuaGJzIiwiZnJhZ21lbnRVcmkiXQ%3D%3D

and then embedding them in the page.

**Comment by ikreymer** [comment]
Will have a fix for this shortly. The issue was due to incomplete rewriting of `data-` attributes, which probably shouldn't be rewritten at all. The result is that it will end up loading: 
https://www.webarchive.org.uk/act/wayback/archive/20211103115244/https://www.bcg.com/en-gb/
which seems to be correct behavior (the site redirects to a locale-specific path when accessed outside of the US)

**Comment by ikreymer** [comment]
Should be fixed in 2.6.1 release.
Can be tested by updating base image to `FROM webrecorder/pywb:2.6.1`

**Comment by anjackson** [comment]
This seems to work much better on DEV now: https://dev.webarchive.org.uk/act/wayback/archive/20211103115244/https://www.bcg.com/en-gb/  which I think is the combined effect of stopping the cooking getting lost, and Ilya's fixes in 2.6.2.
