### ISSUE TITLE
Upgrade to PyWB 2.6.2

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#71]
Should resolve #70

**Comment by ikreymer** [comment]
Should now be 2.6.2, due to regression.

**Comment by anjackson** [comment]
Thanks to @ikreymer pushing the 2.6.2 Docker image, I could test this and found that banner handling was changed [here](https://github.com/webrecorder/pywb/commit/f7bd84cdacdd665ff73ae8d09a202f60be2ebae9). Once the UKWA banners had been updated to use the same `{% autoescape false %}` clauses (d1b3236d530c3730da6c6d7efb75f090b75d5c29), the upgraded version worked fine in the integration tests suite.
