### ISSUE TITLE
2022-Q2 Work Package: UKWA PyWB Support for Document Access 

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#74]
The design re-uses the existing PyWB system to provide single-concurrent-use locks on ‘live’ content drawn from a downstream HTTP document delivery server. https://github.com/ukwa/ukwa-pywb/milestone/2

This is under development on the [custom-viewers branch](https://github.com/ukwa/ukwa-pywb/tree/custom-viewers). Deployment configuration is in [ukwa-services/access/rrwb](https://github.com/ukwa/ukwa-services/tree/master/access/rrwb).

To complete the design, we require the ukwa-pywb service to be modified to: 

- [x] #68 
- [x] Block Content-Disposition: attachment downloads so the rendering is controlled by PyWB.  
- [x] Intercept responses that are not PDF/ePub or web formats, and block them, replacing them with a help page. 
- [x] Add appropriate redirects so all requests go to a fixed timestamp+ARK combination (as the locking mechanism requires both a timestamp and an ARK identifier).  (@anjackson to do this in ukwa-services, I think?)
- [x] Remove UKWA branding and calendar navigation from the document access collection. 
- [x] Provide an interface that meets or exceeds the WCAG 2.1 AA accessibility standard. 
- [x] Display the  NPLD terms of use at the start of a new session, requiring the reader to accept terms. 
- [x] https://github.com/ukwa/ukwa-pywb/issues/93
- [x] Lock page should not say _Archived Web Page Locked_ for documents.

**Comment by ikreymer** [comment]
It might be good to clarify what part of this should happen here in pywb and what is only in the electron NPLD Viewer. Assume that this will only be accessed via the electron app (outside testing), some things might make sense to do there.

>  Support pdf.js and ePub.js wrapping on document access collection. 
This will be part of pywb, part of #85

> Block Content-Disposition: attachment downloads so the rendering is controlled by PyWB. 
If the goal is to just block downloads, Electron provides an elegant way to do this. Removing Content-Disposition alone doesn't prevent a browser from ever downloading, so its a bit more tricky if needed to also be supported in pywb itself. If not, this can be just in the NPLD Viewer.

> Intercept responses that are not PDF/ePub or web formats, and block them, replacing them with a help page.
This will be implemented in pywb. There are already placeholders for this for the `reading-room` collection.

> Add appropriate redirects so all requests go to a fixed timestamp+ARK combination (as the locking mechanism requires both a timestamp and an ARK identifier). 

The live proxying will be in pywb.

> Remove UKWA branding and calendar navigation from the document access collection.

pywb can just display a frame with no banner for this. Should the NPLD viewer have UKWA branding at all, as part of the nav location bar, but no access to calendar?

> Provide an interface that meets or exceeds the WCAG 2.1 AA accessibility standard.

This would be in the NPLD Viewer

> Display the NPLD terms of use at the start of a new session, requiring the reader to accept terms.

This will also be part of the NPLD viewer and not in pywb.

**Comment by anjackson** [comment]
Unfortunately, I think everything on this ticket needs to be part of PyWB (or the NGINX it's deployed with).  The terms of use _may_ need to be displayed by PyWB in some contexts, so it's probably better to add it to PyWB/NGINX.  The same applies to blocking `Content-Disposition` unfortunately.

Accessibility does cover the NPLD Player UI, but also covers the PyWB navigation, calendar pages, and PDF/ePub viewers.  Or course, if we find problems with pdf.js/ePub.js all we can do is raise them upstream, but both projects take accessibility seriously and so this should work out over time. I believe the PyWB templates/pages are already okay in terms of accessibility.

BTW, I've been working on integrating basic accessibility testing into our routine tests. See https://github.com/ukwa/docker-robot-framework/issues/5

**Comment by anjackson** [comment]
As discussed in  Slack, the download block should probably done in the browser. If this causes problems, we'll revisit the issue.

**Comment by anjackson** [comment]
This is looking pretty good now, although printing is not quite right.

**Comment by anjackson** [comment]
So, apparently, the British Library fork of Universal Viewer (https://github.com/britishlibrary/universalviewer) supports PDF and ePub, but also has enhanced features like print layouts, citation support, etc.  This was developed during an earlier iteration of this project, but I'm struggling to find documentation on how it should be used.

As I understand it, we could bundle this as the viewer, but it would mean setting up support for IIIF manifests, and it's not clear if ePub streaming would work.

**Comment by anjackson** [comment]
Noting that the appearance of any collection can be modified by adding alternative template files according the [standard directory structure](https://pywb.readthedocs.io/en/latest/manual/configuring.html#directory-structure).

**Comment by anjackson** [comment]
Implemented branding changes over in https://github.com/ukwa/npld-access-stack/tree/main/pywb which is part of the repository that controls how PyWB is deployed for the NPLD service.

**Comment by anjackson** [comment]
I've moved some follow-on support issues to #100

**Comment by anjackson** [comment]
I've moved #77, #78 to follow-on work tickets, and marked the accessibility requirement as done as you've done all you can at present, and you have indicated you are happy to fold in any issues we find during formal evaluation.

**Comment by anjackson** [comment]
Thanks for all that.
