### ISSUE TITLE
Clean up concurrent usage test

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#8]
The Robot Framework test for concurrent usage would be cleaner and more robust if it used [Switch Browser](http://rtomac.github.io/robotframework-selenium2library/doc/Selenium2Library.html#Switch%20Browser).

Command | arg1 | arg2  |  arg3
-- | -- | -- | --
Open Browser | http://google.com | ff |  
Location Should Be | http://google.com |   |  
Open Browser | http://yahoo.com | ie | 2nd conn
Location Should Be | http://yahoo.com |   |  
Switch Browser | 1 | # index |  
Page Should Contain | I'm feeling lucky |   |  
Switch Browser | 2nd conn | # alias |  
Page Should Contain | More Yahoo! |   |  
Close All Browsers |   |   |

**Comment by ikreymer** [comment]
Added a few improvements here after playing around with Robot, but now realized you assigned it to yourself, hope that's ok!

The main thing not tested currently is the basic auth for locks, wasn't quite sure how to have it specify basic auth (maybe need to use custom FF profile?)

**Comment by anjackson** [comment]
Thanks for doing that @ikreymer! I don't know if the basic auth issue is resolved, but let's close this issue.
