### ISSUE TITLE
Deploy 2.6.7, fixing handling of "&" characters in queries

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-pywb#84]
Tested in both Chrome(100.0.4896.8) and Firefox(100.0b5), maybe related to https://github.com/webrecorder/pywb/issues/707 or https://github.com/nla/outbackcdx/issues/44

This might be more prevalent in general playback, but I've not explored it. Essentially, it looks as though the "&" in a URL is being re-written to the character entity "&amp;", which causes playback to fail because the re-written URL cannot be located in the CDX. Is this a playback or CDX issue? Not sure where encoding is failing

Starting point, the webpage with the link: https://www.webarchive.org.uk/wayback/archive/20141117155105/http://www.otherpeopleschildren.org.uk/index.php

- ![image](https://user-images.githubusercontent.com/18530934/163437233-f212d576-0f8c-4b31-a87d-9c778dacfbfe.png)

**Clicking the link and allowing it to open in the same tab works as expected:** https://www.webarchive.org.uk/wayback/archive/20141117160743/http://www.otherpeopleschildren.org.uk/index.php?option=com_content&view=article&id=158:the-newsletter&catid=34&Itemid=106
- ![image](https://user-images.githubusercontent.com/18530934/163437781-9f2ac564-c899-45b2-8185-281ce2690969.png)

**However, opening the same link so that it opens in a new separate tab, produces this error message:**
- ![image](https://user-images.githubusercontent.com/18530934/163437921-0fb00308-121c-4a59-9e6c-76ca85806933.png)

**The same instance; one opened in a new tab(error), the other in the same tab(works)**
- ![image](https://user-images.githubusercontent.com/18530934/163438765-d6450cc5-fec8-4755-96f6-c7fa5377bf59.png)

**We can see that there are multiple instances available in the CDX:** https://www.webarchive.org.uk/wayback/archive/*/http://www.otherpeopleschildren.org.uk/index.php?option=com_content&view=article&id=158:the-newsletter&catid=34&Itemid=106

- ![image](https://user-images.githubusercontent.com/18530934/163439464-913baa20-70c5-4ba8-b0ec-eb7aef2ae6f6.png)
- opening these instances will fail

Trying to visit https://www.webarchive.org.uk/wayback/archive/*/http://www.otherpeopleschildren.org.uk/index.php?option=com_content&view=article&id=158:the-newsletter&catid=34&Itemid=106 fails because extra characters are included when trying to visit the link, either:
- in a new tab, or
- directly through the calendar view

- ![image](https://user-images.githubusercontent.com/18530934/163441058-2eae6333-8fca-41b9-818b-43bf025f0f09.png)
- ![image](https://user-images.githubusercontent.com/18530934/163441099-8d259e5b-3f80-4469-9e80-36caba9a7e6a.png)

**Comment by anjackson** [comment]
Hmm, yeah, looks like the outer frame is using an escaped URL when creating the iframe:

```
<script>
  var cframe = new ContentFrame({"url": "http://www.otherpeopleschildren.org.uk/index.php?option=com_content&amp;view=article&amp;id=158:the-newsletter&amp;catid=34&amp;Itemid=106" + window.location.hash,
                                 "prefix": "https://www.webarchive.org.uk/wayback/archive/",
                                 "request_ts": "20141117160743",
                                 "iframe": "#replay_iframe"});

```

Not sure if this is PyWB changing behaviour or if it's a problem with the UKWA version [here](https://github.com/ukwa/ukwa-pywb/blob/40a509b83ddba8e35317705855dacdee88386a49/templates/frame_insert.html#L46)

/cc @ikreymer

**Comment by anjackson** [comment]
Ah, darn, looks like I was missing some `autoescape false` sections, comparing with PyWB original templates:

https://github.com/webrecorder/pywb/blob/a6be76642a3844e809c4acabe81afad6e634b201/pywb/templates/frame_insert.html#L17-L36

**Comment by anjackson** [comment]
Pretty sure that's the fix, but rollout will have to wait 'til I'm back.

**Comment by crarugal** [comment]
Great, thanks Andy!

**Comment by anjackson** [comment]
Looks good, pushed update to ukwa-services: https://github.com/ukwa/ukwa-services/commit/b22b0580147af08d7d20f62641d510b0b5e519ec

@GilHoggarth can you update beta and prod access/website services to the latest version, please?
