### ISSUE TITLE
Double forward slash being introduced into cdx search

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-pywb#95]
Redirected links (to the web archive) on the BL website are failing to take users to the latest instance:
https://www.bl.uk/catalogues-and-collections/digital-collections
![image](https://user-images.githubusercontent.com/18530934/181820854-efc1ec9e-c5bc-408a-8717-6ad2016deee1.png)

**Example 1**
Trying to view this URL http://www.bl.uk//onlinegallery/onlineex/unvbrit/ 

Trying to resolve this without a timestamp:
https://www.webarchive.org.uk/wayback/archive/http://www.bl.uk/onlinegallery/onlineex/unvbrit/
![image](https://user-images.githubusercontent.com/18530934/181817522-1f59efcd-0f14-4875-a8d8-eacc9578e7d2.png)

Could be similar to https://github.com/ukwa/ukwa-pywb/issues/29 or https://github.com/ukwa/ukwa-pywb/issues/84

- https://www.webarchive.org.uk/wayback/archive/*/http://www.bl.uk/onlinegallery/onlineex/unvbrit/ will show instances
- but only instances for 2022 are affected https://www.webarchive.org.uk/wayback/archive/20220623112457/http://www.bl.uk/onlinegallery/onlineex/unvbrit/
- previous instances all playback well

**Example 2**
http://www.bl.uk/onlinegallery/onlineex/maps/uk/index.html

https://www.webarchive.org.uk/wayback/archive/*/http://www.bl.uk/onlinegallery/onlineex/maps/uk/index.html

- all instances work, except 2022
- 2022 instance introduces double forward slash when trying to resolve: https://www.webarchive.org.uk/wayback/archive/20220615114757/http://www.bl.uk/onlinegallery/onlineex/maps/uk/index.html
- 
![image](https://user-images.githubusercontent.com/18530934/181818932-223f44f9-38ae-4006-aec0-24b9c4c03282.png)

Both issues persist in QA wayback

**Comment by crarugal** [comment]
https://www.webarchive.org.uk/act/wayback/archive/*/http://www.bbc.co.uk/news 2022 instances seem fine

**Comment by crarugal** [comment]
Could it be that http://www.bl.uk/onlinegallery/onlineex/unvbrit/ and similar BL links were redirecting to webarchive instances pre-2022, and that our crawlers were affected by that when they attempted to crawl those redirect in 2022?

**Comment by crarugal** [comment]
Example
June 23rd capture 2022 http://www.bl.uk/onlinegallery/onlineex/unvbrit/

- https://www.webarchive.org.uk/wayback/archive/20220623112457/http://www.bl.uk/onlinegallery/onlineex/unvbrit/
- webarchive.org.uk/api/query/warc/20220623112457/http://www.bl.uk/onlinegallery/onlineex/unvbrit/

Warc record:
```
WARC/1.0
WARC-Type: response
WARC-Target-URI: http://www.bl.uk/onlinegallery/onlineex/unvbrit/
WARC-Date: 2022-06-23T11:24:57Z
WARC-Payload-Digest: sha1:HLNR6AWVWYCU3YAENY3HYHLIPNWN66X7
WARC-IP-Address: 194.66.233.215
WARC-Record-ID: <urn:uuid:8f0ef9db-6559-47d8-a5ad-0727ea939cb6>
Content-Type: application/http; msgtype=response
Content-Length: 506

HTTP/1.1 301 Moved Permanently
Date: Thu, 23 Jun 2022 11:24:57 GMT
Content-Type: text/html
Content-Length: 162
Connection: close
Location: http://www.webarchive.org.uk/wayback/archive/http://www.bl.uk//onlinegallery/onlineex/unvbrit/
Expires: Fri, 24 Jun 2022 11:24:57 GMT
Cache-Control: max-age=86400
X-Proxy-Pass: DEFAULT-PASSTHRU

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by anjackson** [comment]
I deleted the archived redirect CDX line:

```
uk,bl)/onlinegallery/onlineex/unvbrit 20220623112457 http://www.bl.uk/onlinegallery/onlineex/unvbrit/ text/html 301 HLNR6AWVWYCU3YAENY3HYHLIPNWN66X7 - - 520 335689362 /heritrix/output/frequent-npld/20220606093552/warcs/BL-NPLD-20220623111355199-17035-80~npld-heritrix3-worker-1~8443.warc.gz
```

I had to clear my cache but then the web archive URLs started working.

**Comment by crarugal** [comment]
That's great, thanks Andy, the fix works, and all the links to the archived BL Maps pages redirect as expected.
